// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: watch

#include "../ui.h"

void ui_dateScreen_screen_init(void)
{
    ui_dateScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rili = lv_calendar_create(ui_dateScreen);
    lv_calendar_set_today_date(ui_rili, 2025, 5, 22);
    lv_calendar_set_showed_date(ui_rili, 2025, 5);
    lv_obj_t * ui_rili_header = lv_calendar_header_arrow_create(ui_rili);
    lv_obj_set_width(ui_rili, 240);
    lv_obj_set_height(ui_rili, 280);
    lv_obj_set_align(ui_rili, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rili, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Container7 = lv_obj_create(ui_dateScreen);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 240);
    lv_obj_set_height(ui_Container7, 280);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button13 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_Button13, 240);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, 0);
    lv_obj_set_y(ui_Button13, -115);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label39, 80);
    lv_obj_set_height(ui_Label39, 20);
    lv_obj_set_x(ui_Label39, -60);
    lv_obj_set_y(ui_Label39, 0);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "十秒钟");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Button13);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 60);
    lv_obj_set_y(ui_Switch2, 0);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Button1 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_Button1, 240);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, -40);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label26, 80);
    lv_obj_set_height(ui_Label26, 20);
    lv_obj_set_x(ui_Label26, -60);
    lv_obj_set_y(ui_Label26, -1);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "三十秒");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch6 = lv_switch_create(ui_Button1);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 25);
    lv_obj_set_x(ui_Switch6, 60);
    lv_obj_set_y(ui_Switch6, 0);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);


    ui_Button10 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_Button10, 240);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, 0);
    lv_obj_set_y(ui_Button10, 35);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label37, 80);
    lv_obj_set_height(ui_Label37, 20);
    lv_obj_set_x(ui_Label37, -60);
    lv_obj_set_y(ui_Label37, -1);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "一分钟");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch7 = lv_switch_create(ui_Button10);
    lv_obj_set_width(ui_Switch7, 50);
    lv_obj_set_height(ui_Switch7, 25);
    lv_obj_set_x(ui_Switch7, 60);
    lv_obj_set_y(ui_Switch7, 0);
    lv_obj_set_align(ui_Switch7, LV_ALIGN_CENTER);


    ui_Label52 = lv_label_create(ui_dateScreen);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Label52, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch6, ui_event_Switch6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch7, ui_event_Switch7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dateScreen, ui_event_dateScreen, LV_EVENT_ALL, NULL);

}
