// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: watch

#include "../ui.h"
#include "uart.h"
extern uint8_t dhtbuf[5];


void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 232);
    lv_obj_set_height(ui_Container1, 280);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0x002EFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Container1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Container1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_dianliang = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_dianliang, 71);
    lv_obj_set_height(ui_dianliang, 75);
    lv_obj_set_x(ui_dianliang, -81);
    lv_obj_set_y(ui_dianliang, -72);
    lv_obj_set_align(ui_dianliang, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_dianliang, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_dianliang, 50);
    lv_obj_set_style_arc_width(ui_dianliang, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_dianliang, lv_color_hex(0x00FF1B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_dianliang, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_dianliang, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_dianliang, lv_color_hex(0x00FF1B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dianliang, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dianliang, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_dianliang, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dianliang, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dianliang, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dianliang, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dianliang, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -81);
    lv_obj_set_y(ui_Label1, -77);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "10%");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_shu16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -48);
    lv_obj_set_y(ui_Label2, -3);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "今日步数");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0038FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -82);
    lv_obj_set_y(ui_Label3, 17);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "1234");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_shu16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dianliang2 = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_dianliang2, 55);
    lv_obj_set_height(ui_dianliang2, 55);
    lv_obj_set_x(ui_dianliang2, -82);
    lv_obj_set_y(ui_dianliang2, 83);
    lv_obj_set_align(ui_dianliang2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_dianliang2, LV_STATE_DISABLED);       /// States
    lv_arc_set_range(ui_dianliang2, 0, 45);
    lv_arc_set_value(ui_dianliang2, 34);
    lv_obj_set_style_bg_img_src(ui_dianliang2, &ui_img_wen_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_dianliang2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_dianliang2, lv_color_hex(0xFFAC00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_dianliang2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_dianliang2, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_dianliang2, lv_color_hex(0xFFAC00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dianliang2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dianliang2, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_dianliang2, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dianliang2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dianliang2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dianliang2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dianliang2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_dianliang3 = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_dianliang3, 55);
    lv_obj_set_height(ui_dianliang3, 56);
    lv_obj_set_x(ui_dianliang3, 0);
    lv_obj_set_y(ui_dianliang3, 83);
    lv_obj_set_align(ui_dianliang3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_dianliang3, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_dianliang3, 50);
    lv_obj_set_style_bg_img_src(ui_dianliang3, &ui_img_shidu_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_dianliang3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_dianliang3, lv_color_hex(0x00D4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_dianliang3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_dianliang3, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_dianliang3, lv_color_hex(0x00D4FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dianliang3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dianliang3, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_dianliang3, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dianliang3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dianliang3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dianliang3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dianliang3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -82);
    lv_obj_set_y(ui_Label6, 115);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "20");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_shu16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -1);
    lv_obj_set_y(ui_Label4, 115);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "60%");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_shu16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Container1);
    lv_bar_set_range(ui_Bar1, 0, 200);
    lv_bar_set_value(ui_Bar1, 46, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 193);
    lv_obj_set_height(ui_Bar1, 8);
    lv_obj_set_x(ui_Bar1, -1);
    lv_obj_set_y(ui_Bar1, 33);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x0038FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_dianliang4 = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_dianliang4, 55);
    lv_obj_set_height(ui_dianliang4, 55);
    lv_obj_set_x(ui_dianliang4, 82);
    lv_obj_set_y(ui_dianliang4, 83);
    lv_obj_set_align(ui_dianliang4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_dianliang4, LV_STATE_DISABLED);       /// States
    lv_arc_set_range(ui_dianliang4, 50, 200);
    lv_arc_set_value(ui_dianliang4, 100);
    lv_obj_set_style_arc_width(ui_dianliang4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_dianliang4, lv_color_hex(0xFF0031), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_dianliang4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_dianliang4, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_dianliang4, lv_color_hex(0xFF0003), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dianliang4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dianliang4, 100, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_dianliang4, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dianliang4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dianliang4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dianliang4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dianliang4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_dianliang4);
    lv_img_set_src(ui_Image1, &ui_img_xing_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 3);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 81);
    lv_obj_set_y(ui_Label7, 115);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "73");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_shu16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 37);
    lv_obj_set_y(ui_Label5, -72);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "18 : 32");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_shu20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 20);
    lv_obj_set_y(ui_Label8, -103);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "2025/05/12");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_shu16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label19, 25);
    lv_obj_set_height(ui_Label19, 25);
    lv_obj_set_x(ui_Label19, -81);
    lv_obj_set_y(ui_Label19, -56);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "");
    lv_obj_set_style_bg_img_src(ui_Label19, &ui_img_di_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label20, 25);
    lv_obj_set_height(ui_Label20, 25);
    lv_obj_set_x(ui_Label20, -97);
    lv_obj_set_y(ui_Label20, -1);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "");
    lv_obj_set_style_bg_img_src(ui_Label20, &ui_img_bs_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 86);
    lv_obj_set_y(ui_Label9, -103);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "周一");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label21, 240);
    lv_obj_set_height(ui_Label21, 120);
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, -80);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "");
    lv_obj_add_flag(ui_Label21, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label21, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Label21);
    lv_obj_set_width(ui_Button2, 50);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -70);
    lv_obj_set_y(ui_Button2, -30);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xB7B6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button2, &ui_img_wifi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x0091FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Slider1 = lv_slider_create(ui_Label21);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 50);
    lv_obj_set_height(ui_Slider1, 110);
    lv_obj_set_x(ui_Slider1, 70);
    lv_obj_set_y(ui_Slider1, -2);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Slider1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Slider1);
    lv_obj_set_width(ui_Label36, 40);
    lv_obj_set_height(ui_Label36, 40);
    lv_obj_set_x(ui_Label36, 0);
    lv_obj_set_y(ui_Label36, 30);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "");
    lv_obj_set_style_bg_img_src(ui_Label36, &ui_img_liandu_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Label21);
    lv_obj_set_width(ui_Button11, 50);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_x(ui_Button11, 0);
    lv_obj_set_y(ui_Button11, -30);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xB7B6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button11, &ui_img_guanji_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x0091FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button12 = lv_btn_create(ui_Label21);
    lv_obj_set_width(ui_Button12, 50);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, -70);
    lv_obj_set_y(ui_Button12, 30);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xB7B6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button12, &ui_img_lanya_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x0091FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button14 = lv_btn_create(ui_Label21);
    lv_obj_set_width(ui_Button14, 50);
    lv_obj_set_height(ui_Button14, 50);
    lv_obj_set_x(ui_Button14, 0);
    lv_obj_set_y(ui_Button14, 30);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xB7B6B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button14, &ui_img_shezhi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x0091FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);




}
