// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: watch

#include "../ui.h"

void ui_naozhongScreen_screen_init(void)
{
    ui_naozhongScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_naozhongScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_naozhongScreen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 240);
    lv_obj_set_height(ui_Container6, 280);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container8 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 240);
    lv_obj_set_height(ui_Container8, 280);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label50 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -9);
    lv_obj_set_y(ui_Label50, -119);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "闹钟");
    lv_obj_set_style_text_font(ui_Label50, &ui_font_kaiti20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button20 = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_Button20, 180);
    lv_obj_set_height(ui_Button20, 50);
    lv_obj_set_x(ui_Button20, 0);
    lv_obj_set_y(ui_Button20, -70);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Button20);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -70);
    lv_obj_set_y(ui_Label54, 0);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "AM");
    lv_obj_set_style_text_font(ui_Label54, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Button20);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, -19);
    lv_obj_set_y(ui_Label55, 0);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "18:00");
    lv_obj_set_style_text_font(ui_Label55, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Button20);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 56);
    lv_obj_set_y(ui_Switch4, -1);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);


    ui_Container9 = lv_obj_create(ui_naozhongScreen);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 240);
    lv_obj_set_height(ui_Container9, 280);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container9, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller1 = lv_roller_create(ui_Container9);
    lv_roller_set_options(ui_Roller1, "AM\nPM", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 60);
    lv_obj_set_height(ui_Roller1, 137);
    lv_obj_set_x(ui_Roller1, -79);
    lv_obj_set_y(ui_Roller1, -10);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Roller3 = lv_roller_create(ui_Container9);
    lv_roller_set_options(ui_Roller3, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller3, 60);
    lv_obj_set_height(ui_Roller3, 137);
    lv_obj_set_x(ui_Roller3, -1);
    lv_obj_set_y(ui_Roller3, -9);
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);

    ui_Label56 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, -1);
    lv_obj_set_y(ui_Label56, -98);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "时");
    lv_obj_set_style_text_font(ui_Label56, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, -79);
    lv_obj_set_y(ui_Label57, -97);
    lv_obj_set_align(ui_Label57, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label57, "上午或下午");
    lv_obj_set_style_text_font(ui_Label57, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller4 = lv_roller_create(ui_Container9);
    lv_roller_set_options(ui_Roller4,
                          "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller4, 60);
    lv_obj_set_height(ui_Roller4, 137);
    lv_obj_set_x(ui_Roller4, 72);
    lv_obj_set_y(ui_Roller4, -8);
    lv_obj_set_align(ui_Roller4, LV_ALIGN_CENTER);

    ui_Label59 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, 72);
    lv_obj_set_y(ui_Label59, -97);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "分");
    lv_obj_set_style_text_font(ui_Label59, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button21 = lv_btn_create(ui_Container9);
    lv_obj_set_width(ui_Button21, 70);
    lv_obj_set_height(ui_Button21, 50);
    lv_obj_set_x(ui_Button21, -1);
    lv_obj_set_y(ui_Button21, 107);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Button21, &ui_img_358139227, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button20, ui_event_Button20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_naozhongScreen, ui_event_naozhongScreen, LV_EVENT_ALL, NULL);

}
