// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: watch

#include "../ui.h"

void ui_setsrceen_screen_init(void)
{
    ui_setsrceen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setsrceen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_setsrceen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 240);
    lv_obj_set_height(ui_Container3, 280);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Container3, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Container3, LV_DIR_VER);

    ui_Button3 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button3, 240);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 85);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label23, 40);
    lv_obj_set_height(ui_Label23, 20);
    lv_obj_set_x(ui_Label23, -30);
    lv_obj_set_y(ui_Label23, 0);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "日历");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label22, 35);
    lv_obj_set_height(ui_Label22, 35);
    lv_obj_set_x(ui_Label22, -90);
    lv_obj_set_y(ui_Label22, 0);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "");
    lv_obj_set_style_bg_img_src(ui_Label22, &ui_img_rili_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button4, 240);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 135);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label25, 35);
    lv_obj_set_height(ui_Label25, 35);
    lv_obj_set_x(ui_Label25, -90);
    lv_obj_set_y(ui_Label25, 0);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "");
    lv_obj_set_style_bg_img_src(ui_Label25, &ui_img_742136671, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label24, 80);
    lv_obj_set_height(ui_Label24, 20);
    lv_obj_set_x(ui_Label24, -10);
    lv_obj_set_y(ui_Label24, -1);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "息屏时间");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button6, 240);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, 185);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label27, 35);
    lv_obj_set_height(ui_Label27, 35);
    lv_obj_set_x(ui_Label27, -90);
    lv_obj_set_y(ui_Label27, 0);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "");
    lv_obj_set_style_bg_img_src(ui_Label27, &ui_img_xlxy_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label28, 80);
    lv_obj_set_height(ui_Label28, 20);
    lv_obj_set_x(ui_Label28, -10);
    lv_obj_set_y(ui_Label28, -1);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "心率血氧");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button7, 240);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, 0);
    lv_obj_set_y(ui_Button7, -15);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label29, 35);
    lv_obj_set_height(ui_Label29, 35);
    lv_obj_set_x(ui_Label29, -90);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "");
    lv_obj_set_style_bg_img_src(ui_Label29, &ui_img_twlp_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label30, 80);
    lv_obj_set_height(ui_Label30, 20);
    lv_obj_set_x(ui_Label30, -10);
    lv_obj_set_y(ui_Label30, 0);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "抬腕亮屏");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Button7);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 75);
    lv_obj_set_y(ui_Switch1, 0);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Button9 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button9, 240);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, 0);
    lv_obj_set_y(ui_Button9, -115);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label33, 35);
    lv_obj_set_height(ui_Label33, 35);
    lv_obj_set_x(ui_Label33, -90);
    lv_obj_set_y(ui_Label33, 0);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "");
    lv_obj_set_style_bg_img_src(ui_Label33, &ui_img_dgh_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label34, 80);
    lv_obj_set_height(ui_Label34, 20);
    lv_obj_set_x(ui_Label34, -10);
    lv_obj_set_y(ui_Label34, 0);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "睡眠模式");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Button9);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 75);
    lv_obj_set_y(ui_Switch3, 0);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);


    ui_Button8 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button8, 240);
    lv_obj_set_height(ui_Button8, 50);
    lv_obj_set_x(ui_Button8, 0);
    lv_obj_set_y(ui_Button8, 35);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label31, 35);
    lv_obj_set_height(ui_Label31, 35);
    lv_obj_set_x(ui_Label31, -90);
    lv_obj_set_y(ui_Label31, 0);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "");
    lv_obj_set_style_bg_img_src(ui_Label31, &ui_img_tq_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label32, 80);
    lv_obj_set_height(ui_Label32, 20);
    lv_obj_set_x(ui_Label32, -10);
    lv_obj_set_y(ui_Label32, -1);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "天气");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button15, 240);
    lv_obj_set_height(ui_Button15, 50);
    lv_obj_set_x(ui_Button15, 0);
    lv_obj_set_y(ui_Button15, -65);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label38, 35);
    lv_obj_set_height(ui_Label38, 35);
    lv_obj_set_x(ui_Label38, -90);
    lv_obj_set_y(ui_Label38, 0);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "");
    lv_obj_set_style_bg_img_src(ui_Label38, &ui_img_1969274251, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label35, 80);
    lv_obj_set_height(ui_Label35, 20);
    lv_obj_set_x(ui_Label35, -10);
    lv_obj_set_y(ui_Label35, -1);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "姿态检测");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_Button15);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, 75);
    lv_obj_set_y(ui_Switch5, 0);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);


    ui_Button18 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button18, 240);
    lv_obj_set_height(ui_Button18, 50);
    lv_obj_set_x(ui_Button18, 0);
    lv_obj_set_y(ui_Button18, 235);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label49, 35);
    lv_obj_set_height(ui_Label49, 35);
    lv_obj_set_x(ui_Label49, -90);
    lv_obj_set_y(ui_Label49, 0);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "");
    lv_obj_set_style_bg_img_src(ui_Label49, &ui_img_miaobiao_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Button18);
    lv_obj_set_width(ui_Label47, 80);
    lv_obj_set_height(ui_Label47, 20);
    lv_obj_set_x(ui_Label47, -10);
    lv_obj_set_y(ui_Label47, 0);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "秒表");
    lv_obj_set_style_text_font(ui_Label47, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button19, 240);
    lv_obj_set_height(ui_Button19, 50);
    lv_obj_set_x(ui_Button19, 0);
    lv_obj_set_y(ui_Button19, 285);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label51, 35);
    lv_obj_set_height(ui_Label51, 35);
    lv_obj_set_x(ui_Label51, -90);
    lv_obj_set_y(ui_Label51, 0);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "");
    lv_obj_set_style_bg_img_src(ui_Label51, &ui_img_1809758872, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_Button19);
    lv_obj_set_width(ui_Label48, 80);
    lv_obj_set_height(ui_Label48, 20);
    lv_obj_set_x(ui_Label48, -10);
    lv_obj_set_y(ui_Label48, 0);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "北京时间");
    lv_obj_set_style_text_font(ui_Label48, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button22 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button22, 240);
    lv_obj_set_height(ui_Button22, 50);
    lv_obj_set_x(ui_Button22, 0);
    lv_obj_set_y(ui_Button22, 335);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_Button22);
    lv_obj_set_width(ui_Label61, 35);
    lv_obj_set_height(ui_Label61, 35);
    lv_obj_set_x(ui_Label61, -90);
    lv_obj_set_y(ui_Label61, 0);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "");
    lv_obj_set_style_bg_img_src(ui_Label61, &ui_img_608756609, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Button22);
    lv_obj_set_width(ui_Label58, 80);
    lv_obj_set_height(ui_Label58, 20);
    lv_obj_set_x(ui_Label58, -10);
    lv_obj_set_y(ui_Label58, -1);
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label58, "闹钟");
    lv_obj_set_style_text_font(ui_Label58, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setsrceen, ui_event_setsrceen, LV_EVENT_ALL, NULL);

}
