// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: watch

#include "../ui.h"

void ui_xlxyScreen_screen_init(void)
{
    ui_xlxyScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_xlxyScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_xlxyScreen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 240);
    lv_obj_set_height(ui_Container2, 280);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -7);
    lv_obj_set_y(ui_Label40, -118);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "心率血氧");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Image2, &ui_img_1379335529);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image2, -3);
    lv_obj_set_y(ui_Image2, -46);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label41, 47);
    lv_obj_set_height(ui_Label41, 20);
    lv_obj_set_x(ui_Label41, -52);
    lv_obj_set_y(ui_Label41, 48);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "心率:");
    lv_obj_set_style_text_font(ui_Label41, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label42, 70);
    lv_obj_set_height(ui_Label42, 20);
    lv_obj_set_x(ui_Label42, -70);
    lv_obj_set_y(ui_Label42, 84);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "血氧浓度:");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label43, 30);
    lv_obj_set_height(ui_Label43, 20);
    lv_obj_set_x(ui_Label43, -9);
    lv_obj_set_y(ui_Label43, 48);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "100");
    lv_obj_set_style_text_font(ui_Label43, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -4);
    lv_obj_set_y(ui_Label44, 84);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "100%");
    lv_obj_set_style_text_font(ui_Label44, &ui_font_kaiti16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_xlxyScreen, ui_event_xlxyScreen, LV_EVENT_ALL, NULL);

}
