// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: watch

#ifndef _WATCH_UI_H
#define _WATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "ui_helpers.h"
#include "ui_events.h"

void xingtiao_Animation(lv_obj_t * TargetObject, int delay);
void tiaodon_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_dianliang;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_dianliang2;
extern lv_obj_t * ui_dianliang3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_dianliang4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label21;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button12;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
// SCREEN: ui_dateScreen
void ui_dateScreen_screen_init(void);
void ui_event_dateScreen(lv_event_t * e);
extern lv_obj_t * ui_dateScreen;
extern lv_obj_t * ui_rili;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label39;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label26;
void ui_event_Switch6(lv_event_t * e);
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label37;
void ui_event_Switch7(lv_event_t * e);
extern lv_obj_t * ui_Switch7;
extern lv_obj_t * ui_Label52;
// SCREEN: ui_setsrceen
void ui_setsrceen_screen_init(void);
void ui_event_setsrceen(lv_event_t * e);
extern lv_obj_t * ui_setsrceen;
extern lv_obj_t * ui_Container3;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label22;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label24;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Switch3;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Switch5;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label48;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Label58;
// SCREEN: ui_weatherscreen
void ui_weatherscreen_screen_init(void);
void ui_event_weatherscreen(lv_event_t * e);
extern lv_obj_t * ui_weatherscreen;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label53;
// SCREEN: ui_xlxyScreen
void ui_xlxyScreen_screen_init(void);
void ui_event_xlxyScreen(lv_event_t * e);
extern lv_obj_t * ui_xlxyScreen;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
// SCREEN: ui_miaobiaoScreen
void ui_miaobiaoScreen_screen_init(void);
void ui_event_miaobiaoScreen(lv_event_t * e);
extern lv_obj_t * ui_miaobiaoScreen;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label46;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image7;
// SCREEN: ui_naozhongScreen
void ui_naozhongScreen_screen_init(void);
void ui_event_naozhongScreen(lv_event_t * e);
extern lv_obj_t * ui_naozhongScreen;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label50;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Roller4;
extern lv_obj_t * ui_Label59;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_wen_png);    // assets/wen.png
LV_IMG_DECLARE(ui_img_shidu_png);    // assets/shidu.png
LV_IMG_DECLARE(ui_img_xing_png);    // assets/xing.png
LV_IMG_DECLARE(ui_img_di_png);    // assets/di.png
LV_IMG_DECLARE(ui_img_bs_png);    // assets/bs.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_liandu_png);    // assets/liandu.png
LV_IMG_DECLARE(ui_img_guanji_png);    // assets/guanji.png
LV_IMG_DECLARE(ui_img_lanya_png);    // assets/lanya.png
LV_IMG_DECLARE(ui_img_shezhi_png);    // assets/shezhi.png
LV_IMG_DECLARE(ui_img_rili_png);    // assets/rili.png
LV_IMG_DECLARE(ui_img_742136671);    // assets/息屏.png
LV_IMG_DECLARE(ui_img_xlxy_png);    // assets/xlxy.png
LV_IMG_DECLARE(ui_img_twlp_png);    // assets/twlp.png
LV_IMG_DECLARE(ui_img_dgh_png);    // assets/dgh.png
LV_IMG_DECLARE(ui_img_tq_png);    // assets/tq.png
LV_IMG_DECLARE(ui_img_1969274251);    // assets/姿态.png
LV_IMG_DECLARE(ui_img_miaobiao_png);    // assets/miaobiao.png
LV_IMG_DECLARE(ui_img_1809758872);    // assets/北京时间.png
LV_IMG_DECLARE(ui_img_608756609);    // assets/闹钟.png
LV_IMG_DECLARE(ui_img_9_png);    // assets/9.png
LV_IMG_DECLARE(ui_img_1379335529);    // assets/心跳.png
LV_IMG_DECLARE(ui_img_sx_png);    // assets/sx.png
LV_IMG_DECLARE(ui_img_307400400);    // assets/开始.png
LV_IMG_DECLARE(ui_img_zt_png);    // assets/zt.png
LV_IMG_DECLARE(ui_img_358139227);    // assets/确认.png
LV_IMG_DECLARE(ui_img_0_png);    // assets/0.png
LV_IMG_DECLARE(ui_img_15_png);    // assets/15.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png



LV_FONT_DECLARE(ui_font_kaiti16);
LV_FONT_DECLARE(ui_font_kaiti20);
LV_FONT_DECLARE(ui_font_shu16);
LV_FONT_DECLARE(ui_font_shu20);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
