// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void heart_Animation(lv_obj_t * TargetObject, int delay);
void shuzi_Animation(lv_obj_t * TargetObject, int delay);
void move_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image24;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container3;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label2;
void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label10;
void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label12;
void ui_event_Panel13(lv_event_t * e);
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label13;
void ui_event_Panel14(lv_event_t * e);
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label14;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label23;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Container10;
void ui_event_Panel18(lv_event_t * e);
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label28;
void ui_event_Panel22(lv_event_t * e);
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label30;
void ui_event_Panel23(lv_event_t * e);
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label31;
void ui_event_Panel25(lv_event_t * e);
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label32;
void ui_event_Panel27(lv_event_t * e);
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label33;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
void ui_event_Screen8(lv_event_t * e);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Container22;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
void ui_event_Screen7(lv_event_t * e);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Container18;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label49;
void ui_event_Panel16(lv_event_t * e);
extern lv_obj_t * ui_Panel16;
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
void ui_event_Panel21(lv_event_t * e);
extern lv_obj_t * ui_Panel21;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Label55;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label56;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui____initial_actions0;
void change_txt(uint8_t sport);
void change2_txt(uint8_t sport);

LV_IMG_DECLARE(ui_img_817792301);    // assets/【哲风壁纸】Ios-ios 墙纸 (1).png
LV_IMG_DECLARE(ui_img_596444357);    // assets/静音.png
LV_IMG_DECLARE(ui_img_180574827);    // assets/抬腕亮屏.png
LV_IMG_DECLARE(ui_img_2131476430);    // assets/moon-b-月亮.png
LV_IMG_DECLARE(ui_img_18754430);    // assets/红心.png
LV_IMG_DECLARE(ui_img_1745059841);    // assets/足迹.png
LV_IMG_DECLARE(ui_img_1772208564);    // assets/多云.png
LV_IMG_DECLARE(ui_img_1210737378);    // assets/小雨.png
LV_IMG_DECLARE(ui_img_1225357782);    // assets/大雨.png
LV_IMG_DECLARE(ui_img_1664587152);    // assets/晴朗.png
LV_IMG_DECLARE(ui_img_27480227);    // assets/红心1.png
LV_IMG_DECLARE(ui_img_895372484);    // assets/血氧.png
LV_IMG_DECLARE(ui_img_616669363);    // assets/跑步.png
LV_IMG_DECLARE(ui_img_608756609);    // assets/闹钟.png
LV_IMG_DECLARE(ui_img_157119362);    // assets/记录.png
LV_IMG_DECLARE(ui_img_832424109);    // assets/血氧_画板 1 副本 6.png
LV_IMG_DECLARE(ui_img_1610765691);    // assets/打篮球.png
LV_IMG_DECLARE(ui_img_1391674331);    // assets/行走 (1).png
LV_IMG_DECLARE(ui_img_1837323648);    // assets/游泳.png
LV_IMG_DECLARE(ui_img_2134279843);    // assets/冬奥会-速度滑冰.png
LV_IMG_DECLARE(ui_img_1104748100);    // assets/健走.png
LV_IMG_DECLARE(ui_img_255113753);    // assets/继续.png
LV_IMG_DECLARE(ui_img_933793681);    // assets/暂停.png
LV_IMG_DECLARE(ui_img_177615356);    // assets/暂停1.png
LV_IMG_DECLARE(ui_img_1735873665);    // assets/加.png
LV_IMG_DECLARE(ui_img_1646111717);    // assets/勾勾.png
LV_IMG_DECLARE(ui_img_shuzi1_png);    // assets/shuzi1.png
LV_IMG_DECLARE(ui_img_shuzi2_png);    // assets/shuzi2.png
LV_IMG_DECLARE(ui_img_shuzi3_png);    // assets/shuzi3.png



LV_FONT_DECLARE(ui_font_s1time1);
LV_FONT_DECLARE(ui_font_s2time1);
LV_FONT_DECLARE(ui_font_s3time1);
LV_FONT_DECLARE(ui_font_s7time1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
