// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void change_sport(lv_event_t * e);
void play_time(lv_event_t * e);
void play_sport(lv_event_t * e);
void continue_play(lv_event_t * e);
void over_play(lv_event_t * e);
void stop_play(lv_event_t * e);
void modif_flag(lv_event_t * e);
void set_AlarmClock(lv_event_t * e);
void set_clock(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
