// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "rtc.h"
#include "FreeRTOS.h"
#include "task.h"
extern TaskHandle_t xCount_Handle ;
 

uint8_t flag = 0;

uint8_t keep = 0; //判断运动任务是否删除

uint8_t sport = 0; //判断是什么运动

uint8_t count = 0;	//记录运动次数，最多三次

char  now[10]	;//当前时间小时
 

void clock1()
{
	char *str = lv_label_get_text(ui_Label50);
	char *p	 = lv_label_get_text(ui_Label53);
	RTC_Alarm_AInit(atoi(str),atoi(p));
}


void clock2()
{
	char *str = lv_label_get_text(ui_Label21);
	char *p	 = lv_label_get_text(ui_Label16);
	RTC_Alarm_AInit(atoi(str),atoi(p));
}

void set_clock(lv_event_t * e)
{
	// Your code 
	char str[4];
	
	//flag = 1 代表修改闹钟1的时间
	if(flag == 1)
	{
		lv_roller_get_selected_str(ui_Roller1,str,sizeof(str));
		lv_label_set_text(ui_Label50,str);
		if(lv_roller_get_selected(ui_Roller1) > 11)
		lv_label_set_text(ui_Label54,"PM");
		else lv_label_set_text(ui_Label54,"AM");
		lv_roller_get_selected_str(ui_Roller3,str,sizeof(str));
		lv_label_set_text(ui_Label53,str);
 
		flag = 0;
		clock1();
	}
	
	else if(flag == 2)
	{
		lv_roller_get_selected_str(ui_Roller1,str,sizeof(str));
		lv_label_set_text(ui_Label21,str);
		if(lv_roller_get_selected(ui_Roller1) > 11)
		lv_label_set_text(ui_Label17,"PM");
		else lv_label_set_text(ui_Label17,"AM");
		lv_roller_get_selected_str(ui_Roller3,str,sizeof(str));
		lv_label_set_text(ui_Label16,str);
	 
		flag = 0;
		clock2();
	 
	}
		
	//先判断Panel21的状态，如果是隐藏就执行if里的代码，如果非隐藏，说明已经存在一个闹钟了，就执行else里的语句
	else if(flag == 0)
	{
		if	(!lv_obj_is_visible(ui_Panel21))
		{

			lv_roller_get_selected_str(ui_Roller1,str,sizeof(str));
			lv_label_set_text(ui_Label50,str);
			if(lv_roller_get_selected(ui_Roller1) > 11)
			lv_label_set_text(ui_Label54,"PM");
			else lv_label_set_text(ui_Label54,"AM");
			lv_roller_get_selected_str(ui_Roller3,str,sizeof(str));
			lv_label_set_text(ui_Label53,str);

			lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_HIDDEN); 
			
			clock1();
		}
		else if(!lv_obj_is_visible(ui_Panel16))
		{
			lv_roller_get_selected_str(ui_Roller1,str,sizeof(str));
			lv_label_set_text(ui_Label21,str);
			if(lv_roller_get_selected(ui_Roller1) > 11)
			lv_label_set_text(ui_Label17,"PM");
			else lv_label_set_text(ui_Label17,"AM");
			lv_roller_get_selected_str(ui_Roller3,str,sizeof(str));
			lv_label_set_text(ui_Label16,str);
			
			 lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_HIDDEN); 
			clock2();
		}
	}
	
}

void play_sport(lv_event_t * e)
{
	// Your code here
	//vTaskDelay(3000);  // 延时1000ms
	vTaskResume(xCount_Handle);
	if(keep == 1)
	{
		create_sport();
		keep = 0;
	}
	char *p = lv_label_get_text(ui_Label1);	//当前时间小时
	char *q = lv_label_get_text(ui_Label4);	//当前时间分钟
	snprintf(now,sizeof(now),"%s:%s",p,q);
	
}

void modif_flag(lv_event_t * e)
{
	// Your code here
	
	  // 获取触发事件的组件
    lv_obj_t * target = lv_event_get_target(e);
 
    // 比较名称
    if (target == ui_Panel21) {
        flag = 1; // 如果是 ui_Panel21，设置 flag = 1
    } else {
        flag = 2; // 否则，设置 flag = 2
    }
}

void set_AlarmClock(lv_event_t * e)
{
	// Your code here
		  // 获取触发事件的组件
    lv_obj_t * target = lv_event_get_target(e);
 
    // 比较名称
    if (target == ui_Switch1) 
	{
        clock1(); // 如果是 ui_Panel21，设置 flag = 1
    } else {
        clock2(); // 否则，设置 flag = 2
    }
}


void play_time(lv_event_t * e)
{

	
}


void continue_play(lv_event_t * e)
{
	// Your code here
	//继续运动
	vTaskResume(xCount_Handle);
}

void over_play(lv_event_t * e)
{
	// Your code here
	//先得到数据
	char * minute = lv_label_get_text(ui_Label42);
	char * hour = lv_label_get_text(ui_Label40); 
	char * second = lv_label_get_text(ui_Label44);
	char * hot = lv_label_get_text(ui_Label46);
	char str[20];
	snprintf(str,sizeof(str),"%s:%s:%s",hour,minute,second);
	printf("000000000000000000000000===========%s\r\n",str);
	
	//将任务删除，把数据保存
	vTaskDelete(xCount_Handle);
	keep = 1;
	
	//将结束界面继续隐藏，运动界面继续展示
	lv_obj_add_flag(ui_Container22, LV_OBJ_FLAG_HIDDEN); 
	lv_obj_clear_flag(ui_Container23, LV_OBJ_FLAG_HIDDEN); 
	
	//判断是什么运动
	if(sport == 1)
	{
		//篮球
		//取消隐藏
		if(count == 0)
		{
			//取消隐藏第一个
			lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_HIDDEN); 
			//lv_label_set_text(ui_Label29,"篮球");
			change_txt(sport);
			lv_label_set_text(ui_Label48,now);
			lv_label_set_text(ui_Label47,hot);
			lv_label_set_text(ui_Label35,str);
		}
		else if(count == 1)
		{
			//取消隐藏第二个
			lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_HIDDEN); 
			change2_txt(sport);
			lv_label_set_text(ui_Label61,now);
			lv_label_set_text(ui_Label60,hot);
			lv_label_set_text(ui_Label57,str);	
			printf("count ================ 1\r\n");
		}
		
	}
	else if(sport == 2)
	{
		//户外跑步
				if(count == 0)
		{
			//取消隐藏第一个
			lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_HIDDEN); 
			//lv_label_set_text(ui_Label29,"篮球");
			change_txt(sport);
			lv_label_set_text(ui_Label48,now);
			lv_label_set_text(ui_Label47,hot);
			lv_label_set_text(ui_Label35,str);
		}
		else if(count == 1)
		{
			//取消隐藏第二个
			lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_HIDDEN); 
			change2_txt(sport);
			lv_label_set_text(ui_Label61,now);
			lv_label_set_text(ui_Label60,hot);
			lv_label_set_text(ui_Label57,str);	
			printf("count ================ 1\r\n");
		}
		
	}
	else if(sport == 3)
	{
		//游泳
				if(count == 0)
		{
			//取消隐藏第一个
			lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_HIDDEN); 
			//lv_label_set_text(ui_Label29,"篮球");
			change_txt(sport);
			lv_label_set_text(ui_Label48,now);
			lv_label_set_text(ui_Label47,hot);
			lv_label_set_text(ui_Label35,str);
		}
		else if(count == 1)
		{
			//取消隐藏第二个
			lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_HIDDEN); 
			change2_txt(sport);
			lv_label_set_text(ui_Label61,now);
			lv_label_set_text(ui_Label60,hot);
			lv_label_set_text(ui_Label57,str);	
			printf("count ================ 1\r\n");
		}
	}
	else if(sport == 4)
	{
		//滑冰
				if(count == 0)
		{
			//取消隐藏第一个
			lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_HIDDEN); 
			//lv_label_set_text(ui_Label29,"篮球");
			change_txt(sport);
			lv_label_set_text(ui_Label48,now);
			lv_label_set_text(ui_Label47,hot);
			lv_label_set_text(ui_Label35,str);
		}
		else if(count == 1)
		{
			//取消隐藏第二个
			lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_HIDDEN); 
			change2_txt(sport);
			lv_label_set_text(ui_Label61,now);
			lv_label_set_text(ui_Label60,hot);
			lv_label_set_text(ui_Label57,str);	
			printf("count ================ 1\r\n");
		}
	}
	else if(sport == 5)
	{
		//健走
				if(count == 0)
		{
			//取消隐藏第一个
			lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_HIDDEN); 
			//lv_label_set_text(ui_Label29,"篮球");
			change_txt(sport);
			lv_label_set_text(ui_Label48,now);
			lv_label_set_text(ui_Label47,hot);
			lv_label_set_text(ui_Label35,str);
		}
		else if(count == 1)
		{
			//取消隐藏第二个
			lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_HIDDEN); 
			change2_txt(sport);
			lv_label_set_text(ui_Label61,now);
			lv_label_set_text(ui_Label60,hot);
			lv_label_set_text(ui_Label57,str);	
			printf("count ================ 1\r\n");
		}
	}
	

	count++;
	if(count >1)count = 0;

	
 
	
	//将数据恢复成0
	lv_label_set_text(ui_Label46,"0");
	lv_label_set_text(ui_Label44,"00");
	lv_label_set_text(ui_Label42, "00");
	lv_label_set_text(ui_Label40, "00");
}

void stop_play(lv_event_t * e)
{
	// Your code here
	//挂起
	vTaskSuspend(xCount_Handle);
	
}


void change_sport(lv_event_t * e)
{
	// Your code here
		  // 获取触发事件的组件
    lv_obj_t * target = lv_event_get_target(e);
 
    // 比较名称
    if (target == ui_Panel18) 
	{
        sport = 1; // 如果是 ui_Panel21，设置 flag = 1
    } 
	else if(target == ui_Panel22) 
	{
        sport = 2; // 否则，设置 flag = 2
    }
	else if(target == ui_Panel23) 
	{
        sport = 3; // 否则，设置 flag = 2
    }
	else if(target == ui_Panel25) 
	{
        sport = 4; // 否则，设置 flag = 2
    }
	else if(target == ui_Panel27) 
	{
        sport = 5; // 否则，设置 flag = 2
    }
}
