// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_ass[2] = {0x15A1E4, 0x15A1E4};
const ui_theme_variable_t _ui_theme_alpha_ass[2] = {255, 180};

const ui_theme_variable_t _ui_theme_color_dss[2] = {0x575252, 0x575252};
const ui_theme_variable_t _ui_theme_alpha_dss[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

